grails-app/domain/quiz2/Evento.groovy
package quiz2

class Evento {

    String nombre
    String descripcion
    Date fechaInicio
    Date fechaFin
    int edadPermitida

    static constraints = {
    }
}

grails-app/domain/quiz2/Usuario.groovy
package quiz2

class Usuario {

    String nombre
    String apellido
    String cedula
    String email
    Date fechaNacimiento

    static hasMany = [eventos: Evento]
    static constraints = {
        email email: true
    }
}

grails-app/controllers/quiz2/EventoController.groovy
package quiz2

import grails.validation.ValidationException

import java.sql.Time

import static org.springframework.http.HttpStatus.*

class EventoController {

    EventoService eventoService

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond eventoService.list(params), model: [eventoCount: eventoService.count()]
    }


    def show(Long id) {
        respond eventoService.get(id)
    }

    def create() {

    }

    def save(String nombre, String descripcion, Date fechaInicio, Date fechaFin, int edadPermitida, String horaInicio, String horaFin) {

        def calIni = Calendar.getInstance()
        calIni.setTime(fechaInicio)

        def calFin = Calendar.getInstance()
        calFin.setTime(fechaFin)

        def horaMinInicio = horaInicio.split(":")
        def horaMinFin = horaFin.split(":")

        calIni.set(Calendar.HOUR_OF_DAY, Integer.valueOf(horaMinInicio[0]))
        calIni.set(Calendar.MINUTE, Integer.valueOf(horaMinInicio[1]))

        calFin.set(Calendar.HOUR_OF_DAY, Integer.valueOf(horaMinFin[0]))
        calFin.set(Calendar.MINUTE, Integer.valueOf(horaMinFin[1]))

        def evento = new Evento()
        evento.setNombre(nombre)
        evento.setDescripcion(descripcion)

        evento.setFechaInicio(calIni.getTime())
        evento.setFechaFin(calFin.getTime())
        evento.setEdadPermitida(edadPermitida)

        evento.save(flush: true, failOnError: true)

        redirect(uri: '/')
    }

    def edit(Long id) {
        respond eventoService.get(id)
    }

    def update(Evento evento) {
        if (evento == null) {
            notFound()
            return
        }

        try {
            eventoService.save(evento)
        } catch (ValidationException e) {
            respond evento.errors, view: 'edit'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'evento.label', default: 'Evento'), evento.id])
                redirect evento
            }
            '*' { respond evento, [status: OK] }
        }
    }

    def delete(Long id) {
        if (id == null) {
            notFound()
            return
        }

        eventoService.delete(id)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'evento.label', default: 'Evento'), id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'evento.label', default: 'Evento'), params.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NOT_FOUND }
        }
    }
}

grails-app/controllers/quiz2/UrlMappings.groovy
package quiz2

class UrlMappings {

    static mappings = {
        "/$controller/$action?/$id?(.$format)?"{
            constraints {
                // apply constraints here
            }
        }

        "/"(view:"/index")
        "500"(view:'/error')
        "404"(view:'/notFound')
    }
}

grails-app/controllers/quiz2/UsuarioController.groovy
package quiz2

import grails.validation.ValidationException
import static org.springframework.http.HttpStatus.*

class UsuarioController {

    UsuarioService usuarioService

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond usuarioService.list(params), model:[usuarioCount: usuarioService.count()]
    }

    def agregarEvento(){

        [eventos: Evento.findAll()]
    }

    def asignarEvento(){

        def evento = Evento.findById(params.id as Long)

        print "nombre: " + evento.nombre

        def usuario = Usuario.first()

        usuario.addToEventos(evento)
        usuario.save(flush: true, failOnError:true)



        return false
    }


    def nuevo() {

    }

    def create(String nombre, String apellido, String cedula, String email, Date fechaNacimiento) {

        def usuario = new Usuario()
        usuario.setNombre(nombre)
        usuario.setApellido(apellido)
        usuario.setCedula(cedula)
        usuario.setEmail(email)
        usuario.setFechaNacimiento(fechaNacimiento)



        usuario.save(flush:true, failOnError:true)

        redirect(uri: '/')

    }

    def save(Usuario usuario) {
        if (usuario == null) {
            notFound()
            return
        }

        try {
            usuarioService.save(usuario)
        } catch (ValidationException e) {
            respond usuario.errors, view:'index'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'usuario.label', default: 'Usuario'), usuario.id])
                redirect usuario
            }
            '*' { respond usuario, [status: CREATED] }
        }
    }

    def edit(Long id) {
        respond usuarioService.get(id)
    }

    def update(Usuario usuario) {
        if (usuario == null) {
            notFound()
            return
        }

        try {
            usuarioService.save(usuario)
        } catch (ValidationException e) {
            respond usuario.errors, view:'agregarEvento'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'usuario.label', default: 'Usuario'), usuario.id])
                redirect usuario
            }
            '*'{ respond usuario, [status: OK] }
        }
    }

    def delete(Long id) {
        if (id == null) {
            notFound()
            return
        }

        usuarioService.delete(id)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'usuario.label', default: 'Usuario'), id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'usuario.label', default: 'Usuario'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/evento/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <title>Evento</title>
    </head>
    <body>
    <h1>Nuevo evento</h1>

    <g:form class="form" action="save">

        <div class="form-group">
            <label for="nombre" >Nombre</label>
            <input id="nombre" name="nombre" class="form-control" required>
        </div>

        <div class="form-group">
            <label for="descripcion" >Descripcion</label>
            <input id="descripcion" name="descripcion" class="form-control" required>
        </div>


        <div class="form-group">
            <label for="fechaInicio" >Fecha de Inicio</label>
            <input id="fechaInicio" name="fechaInicio" type="date" class="form-control" required>
        </div>

        <div class="form-group">
            <label for="horaInicio" >Hora de Inicio</label>
            <input id="horaInicio" name="horaInicio" type="time" class="form-control" required>
        </div>
        <div class="form-group">
            <label for="fechaFin" >Fecha de Fin</label>
            <input id="fechaFin" name="fechaFin" type="date" class="form-control" required>
        </div>

        <div class="form-group">
            <label for="horaFin" >Hora de Fin</label>
            <input id="horaFin" name="horaFin" type="time" class="form-control" required>
        </div>

        <div class="form-group">
            <label for="edadPermitida" >Edad permitida</label>
            <input id="edadPermitida" type="number" name="edadPermitida" class="form-control" required>
        </div>

    %{--<button type="reset" class="btn  btn-warning">Cancelar</button>--}%
        <button type="reset" class="newsletter_button trans_300"><span>Cancelar</span></button>
        <button type="submit" class="newsletter_button trans_300"><span>OK</span></button>
    %{--<button type="submit" class="btn  btn-primary">OK</button>--}%
    </g:form>
    </body>
</html>

grails-app/views/evento/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'evento.label', default: 'Evento')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#edit-evento" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="edit-evento" class="content scaffold-edit" role="main">
            <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.evento}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.evento}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.evento}" method="PUT">
                <g:hiddenField name="version" value="${this.evento?.version}" />
                <fieldset class="form">
                    <f:all bean="evento"/>
                </fieldset>
                <fieldset class="buttons">
                    <input class="save" type="submit" value="${message(code: 'default.button.update.label', default: 'Update')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/evento/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'evento.label', default: 'Evento')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#list-evento" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="list-evento" class="content scaffold-list" role="main">
            <h1><g:message code="default.list.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:table collection="${eventoList}" />

            <div class="pagination">
                <g:paginate total="${eventoCount ?: 0}" />
            </div>
        </div>
    </body>
</html>

grails-app/views/evento/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'evento.label', default: 'Evento')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#show-evento" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="show-evento" class="content scaffold-show" role="main">
            <h1><g:message code="default.show.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:display bean="evento" />
            <g:form resource="${this.evento}" method="DELETE">
                <fieldset class="buttons">
                    <g:link class="edit" action="edit" resource="${this.evento}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                    <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/usuario/agregarEvento.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main"/>

    <title><g:message code="default.edit.label" args="[entityName]"/></title>
</head>

<body>

<h1>Eventos</h1>

<table class="table table-hover">
    <thead>
    <tr>

        <th>Nombre</th>
        <th>Descripción</th>
        <th>Fecha Inicio</th>
        <th>Fecha Fin</th>
        <th>Agregar</th>


    </tr>

    </thead>

    <tbody>

    <g:each in="${eventos}" var="evento">
        <tr>
            <td>${evento.nombre}</td>
            <td>${evento.descripcion}</td>
            <td><g:formatDate format="dd-MM-yyyy HH:mm" date="${evento.fechaInicio}"/></td>
            <td><g:formatDate format="dd-MM-yyyy HH:mm" date="${evento.fechaFin}"/></td>
            <td> <button class="btn btn-success" onclick="agregarEvento(${evento.id})"  >Agregar</button></td>
        </tr>
    </g:each>
    </tbody>
</table>

<script>

    $(document).ready(function () {


    });

    function agregarEvento(id) {

        $.ajax({
            type: 'POST',
            data: {id:id},
            url: "${g.createLink(controller:'usuario',action:'asignarEvento')}",
            success: function (res) {


            }
        });

    }

</script>

</body>
</html>

grails-app/views/usuario/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <title>Crear usuario</title>
    </head>
    <body>

    <h1>Usuarios</h1>


    </body>
</html>

grails-app/views/usuario/nuevo.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />

        <title>Nuevo usuario</title>
    </head>
    <body>
      <h1>Nuevo usuario</h1>

    <g:form class="form" action="create">

        <div class="form-group">
            <label for="nombre" >Nombre</label>
            <input id="nombre" name="nombre" class="form-control" required>
        </div>

        <div class="form-group">
            <label for="apellido" >Apellido</label>
            <input id="apellido" name="apellido" class="form-control" required>
        </div>

        <div class="form-group">
            <label for="cedula" >Cedula</label>
            <input id="cedula" name="cedula" class="form-control" required>
        </div>

        <div class="form-group">
            <label for="fechaNacimiento" >Fecha de Nacimiento</label>
            <input id="fechaNacimiento" name="fechaNacimiento" type="date" class="form-control" required>
        </div>

        <div class="form-group">
            <label for="email" >Correo</label>
            <input id="email" type="email" name="email" class="form-control" required>
        </div>

        %{--<button type="reset" class="btn  btn-warning">Cancelar</button>--}%
        <button type="reset" class="newsletter_button trans_300"><span>Cancelar</span></button>
        <button type="submit" class="newsletter_button trans_300"><span>OK</span></button>
        %{--<button type="submit" class="btn  btn-primary">OK</button>--}%
    </g:form>
    </body>
</html>

grails-app/views/usuario/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'usuario.label', default: 'Usuario')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#show-usuario" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="show-usuario" class="content scaffold-show" role="main">
            <h1><g:message code="default.show.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:display bean="usuario" />
            <g:form resource="${this.usuario}" method="DELETE">
                <fieldset class="buttons">
                    <g:link class="edit" action="edit" resource="${this.usuario}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                    <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>